// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('views/RecipeView', ['views/ProtoView', 'models/RecipeModel'], function(ProtoView, RecipeModel) {
    var RecipeView, _ref;

    RecipeView = (function(_super) {
      __extends(RecipeView, _super);

      function RecipeView() {
        _ref = RecipeView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RecipeView.prototype.model = RecipeModel;

      RecipeView.prototype.template = '#recipe-template';

      RecipeView.prototype.className = 'recipe-b';

      RecipeView.prototype.events = {
        'click #js-remove': 'remove'
      };

      RecipeView.prototype.initialize = function() {
        RecipeView.__super__.initialize.apply(this, arguments);
        this.model.on('all', _.bind(this.render, this));
        return this;
      };

      RecipeView.prototype.toggleExpand = function() {
        return this.$el.toggleClass('is-expanded');
      };

      RecipeView.prototype.remove = function(e) {
        var _this = this;

        if (!e) {
          return;
        }
        e.stopPropagation();
        if (confirm("Are you sure whant to remove \"" + (this.model.get('header')) + "\" item?")) {
          this.$el.fadeOut(500, function() {
            return _this.model.destroy();
          });
        }
        return this;
      };

      return RecipeView;

    })(ProtoView);
    return RecipeView;
  });

}).call(this);
