// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('views/RecipeView', ['views/ProtoView', 'models/RecipeModel'], function(ProtoView, RecipeModel) {
    var RecipeView, _ref;

    RecipeView = (function(_super) {
      __extends(RecipeView, _super);

      function RecipeView() {
        _ref = RecipeView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RecipeView.prototype.template = '#recipe-template';

      RecipeView.prototype.className = 'recipe-b cf';

      RecipeView.prototype.events = {
        'click .recipe-preview-e': 'toggleExpand',
        'click #js-remove': 'remove',
        'click #js-edit': 'edit',
        'click #js-cancel': 'cancel'
      };

      RecipeView.prototype.initialize = function() {
        RecipeView.__super__.initialize.apply(this, arguments);
        this.model.on('change', _.bind(this.render, this));
        return this;
      };

      RecipeView.prototype.render = function() {
        RecipeView.__super__.render.apply(this, arguments);
        this.bindAttributes();
        return this;
      };

      RecipeView.prototype.bindAttributes = function() {
        return this.$el.toggleClass('is-edit', !!this.model.get('isEditMode'));
      };

      RecipeView.prototype.toggleExpand = function() {
        return this.$el.toggleClass('is-expanded');
      };

      RecipeView.prototype.remove = function(e) {
        var _this = this;

        if (!e) {
          return;
        }
        e.stopPropagation();
        if (confirm("Are you sure whant to remove \"" + (this.model.get('header')) + "\" item?")) {
          this.$el.fadeOut(500, function() {
            return _this.model.destroy();
          });
        }
        return this;
      };

      RecipeView.prototype.edit = function(e) {
        if (!e) {
          return;
        }
        e.stopPropagation();
        return this.model.toggleAttr('isEditMode');
      };

      RecipeView.prototype.cancel = function(e) {
        if (!e) {
          return;
        }
        e.stopPropagation();
        this.model.set('isEditMode', false);
        return App.$bodyHtml.animate({
          'scrollTop': this.$el.offset().top - 150
        });
      };

      return RecipeView;

    })(ProtoView);
    return RecipeView;
  });

}).call(this);
