// Generated by CoffeeScript 1.6.2
(function() {
  define('controllers/PagesController', ['views/pages/main'], function(main) {
    var Controller;

    Controller = (function() {
      function Controller() {
        this.main = main;
      }

      return Controller;

    })();
    return new Controller;
  });

}).call(this);
